### ISSUE TITLE
Extended scan response has legacy PDU bit event type bit set

### ISSUE THREAD

**Issue by BenjaminLawson** [google/rootcanal#23]
Extended scan response advertising reports incorrectly have the legacy PDU event type bit set:
https://github.com/google/rootcanal/blob/92b86723b5850f8e0b2d32fb0c998016bc4c2ce9/model/controller/link_layer_controller.cc#L4966

**Comment by hchataing** [comment]
Fixed by 023c89e7ff61c4451bfe9c7cacf00339bf6018b0
